// Resource paths + the environment passed to the agent-host utilityProcess.
//
// The workspace (~/.accountant24 by default) holds the ledger + auth.json +
// models.json; PATH exposes the vendored native tools (hledger/pdftotext/
// tesseract) to the agent's bash/tool subprocesses; TESSDATA_PREFIX points at
// the OCR data.
//
// ACCOUNTANT24_WORKSPACE is the single channel that names the workspace: set
// by the `--workspace` launch flag (cli.ts) or by the caller's environment, read
// by workspaceDir() here and inherited by the agent host (agentEnv), the bundled
// extension, hledger subprocesses, and the test helpers.

import { existsSync } from "node:fs";
import { homedir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { app } from "electron";
import type { AgentHostConfig, AgentHostSkill } from "../shared/agentHost";

/** ~/.accountant24 — the workspace when neither --workspace nor
 *  ACCOUNTANT24_WORKSPACE is set. */
export function defaultWorkspaceDir(): string {
  return path.join(homedir(), ".accountant24");
}

/** The workspace: the agent's cwd and the home of the ledger/auth/models.
 *  ACCOUNTANT24_WORKSPACE when set and non-empty, else the default. */
export function workspaceDir(): string {
  const env = process.env.ACCOUNTANT24_WORKSPACE;
  return env && env.length > 0 ? env : defaultWorkspaceDir();
}

/** <workspace>/plugins — one self-contained folder per installed plugin
 *  (Agent Plugins standard: a plugin.json plus skills/<name>/SKILL.md). The
 *  skills of every installed plugin are passed to the agent child. */
export function pluginsDir(): string {
  return path.join(workspaceDir(), "plugins");
}

/** <workspace>/sessions — pi's session files, one JSONL per chat thread.
 *  Passed to the agent child via `--session-dir`. */
export function sessionsDir(): string {
  return path.join(workspaceDir(), "sessions");
}

/** <workspace>/ledger/main.journal — the ledger's entry point (includes the
 *  other journal files). */
export function mainJournalPath(): string {
  return path.join(workspaceDir(), "ledger", "main.journal");
}

/** <workspace>/app-settings.json — app-owned settings (distinct from pi's
 *  own settings.json in the same folder). */
export function appSettingsPath(): string {
  return path.join(workspaceDir(), "app-settings.json");
}

/** Dir holding vendored bin/ + tessdata/ + the extension bundle.
 *  Dev: packages/desktop/resources. Packaged: the app's resources dir
 *  (electron-builder extraResources land directly under it). */
function resourceDir(): string {
  return app.isPackaged ? process.resourcesPath : path.join(app.getAppPath(), "resources");
}

/** The app's own documentation, bundled as plain markdown (one file per docs
 *  page, generated by scripts/bundle-extension.ts). Exported to the agent host
 *  as ACCOUNTANT24_DOCS; the extension names the folder in the prompt's <docs-folder>
 *  block so skills can read the docs of the running version. */
export function docsDir(): string {
  return path.join(resourceDir(), "docs");
}

/** Dir holding the vendored native tools (hledger/pdftotext/tesseract). Prepended
 *  to the agent child's PATH; also used to resolve a tool's absolute path when we
 *  run one directly from the main process (which does NOT inherit that PATH). */
export function binDir(): string {
  return path.join(resourceDir(), "bin");
}

/** The bundled extension passed to `pi -e`. Loaded as JS in both dev and
 *  packaged (Electron-as-Node can't parse the TS source); produced by
 *  scripts/bundle-extension.ts. */
export function extensionPath(): string {
  return path.join(resourceDir(), "accountant24-extension.js");
}

/** The static system prompt passed to `pi --system-prompt`. pi replaces its
 *  coding-agent preamble with this file's contents but still assembles its
 *  native sections (the <available_skills> block, date/cwd) around it; the
 *  extension then appends the dynamic tools/context sections per turn. Copied
 *  next to the extension bundle by scripts/bundle-extension.ts. */
export function systemPromptPath(): string {
  return path.join(resourceDir(), "system.md");
}

/** Built agent-host utilityProcess entry — emitted as a sibling of the main
 *  bundle (out/main/agent-host.js) in both dev and packaged builds, so it
 *  resolves relative to this module's own URL. */
export function agentHostEntryPath(): string {
  return fileURLToPath(new URL("./agent-host.js", import.meta.url));
}

/** Static config for the agent host, passed as JSON in argv[2] at fork time.
 *  Skills are resolved by the caller (agent/plugins.ts) rather than here: they
 *  depend on the app settings, and this module must stay a pure path resolver
 *  that settings.ts can import. */
export function agentHostConfig(skills: AgentHostSkill[]): AgentHostConfig {
  return {
    workspaceDir: workspaceDir(),
    sessionsDir: sessionsDir(),
    skills,
    extensionPath: extensionPath(),
    systemPromptPath: systemPromptPath(),
  };
}

/** Env overrides for the agent host + in-process SDK: workspace + vendored
 *  tools. PI_CODING_AGENT_DIR is redundant for the host itself (agentDir is
 *  passed explicitly) but kept for env parity in the agent's subprocesses. */
export function agentEnv(): NodeJS.ProcessEnv {
  const workspace = workspaceDir();
  const env: NodeJS.ProcessEnv = {
    ...process.env,
    ACCOUNTANT24_WORKSPACE: workspace,
    PI_CODING_AGENT_DIR: workspace,
  };
  const res = resourceDir();
  const bin = binDir();
  if (existsSync(bin)) env.PATH = `${bin}${path.delimiter}${env.PATH ?? ""}`;
  const tessdata = path.join(res, "tessdata");
  if (existsSync(tessdata)) env.TESSDATA_PREFIX = tessdata;
  const docs = docsDir();
  if (existsSync(docs)) env.ACCOUNTANT24_DOCS = docs;
  return env;
}
